baseURL = "/"
languageCode = "en-us"
title = "Flatland Church"
assetsDir = "assets"

[outputs]
home = ["HTML", "RSS", "Algolia"]
section = ["HTML", "RSS", "JSON"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "permalink", "content"]
params = ["categories", "series", "tags"]

[markup.goldmark.renderer]
unsafe= true
